services:
  postservice.api:
    image: ${DOCKER_REGISTRY-}postserviceapi
    build:
      context: .
      dockerfile: PostService/Dockerfile

  postgres:
    container_name: postservice-postgres-db
    image: postgres:latest
    environment:
      POSTGRES_DB: "PostServiceDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5433:5432"
  
  
volumes:
  postgres-data:
